In [2]:
!wget https://github.com/DataTalksClub/nyc-tlc-data/releases/download/green/green_tripdata_2019-10.csv.gz

--2025-01-25 15:17:49--  https://github.com/DataTalksClub/nyc-tlc-data/releases/download/green/green_tripdata_2019-10.csv.gz
Resolving github.com (github.com)... 140.82.121.3
Connecting to github.com (github.com)|140.82.121.3|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://objects.githubusercontent.com/github-production-release-asset-2e65be/513814948/ea580e9e-555c-4bd0-ae73-43051d8e7c0b?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=releaseassetproduction%2F20250125%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20250125T121749Z&X-Amz-Expires=300&X-Amz-Signature=c9e4c76cc3236a9ea7a80473480d8bb4e4e964bccfddaa877501b3f1f32527f3&X-Amz-SignedHeaders=host&response-content-disposition=attachment%3B%20filename%3Dgreen_tripdata_2019-10.csv.gz&response-content-type=application%2Foctet-stream [following]
--2025-01-25 15:17:50--  https://objects.githubusercontent.com/github-production-release-asset-2e65be/513814948/ea580e9e-555c-4bd0-ae73-43051d8e7c0b?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=releaseassetproduction%2F20250125%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20250125T121749Z&X-Amz-Expires=300&X-Amz-Signature=c9e4c76cc3236a9ea7a80473480d8bb4e4e964bccfddaa877501b3f1f32527f3&X-Amz-SignedHeaders=host&response-content-disposition=attachment%3B%20filename%3Dgreen_tripdata_2019-10.csv.gz&response-content-type=application%2Foctet-stream
Resolving objects.githubusercontent.com (objects.githubusercontent.com)... 185.199.110.133, 185.199.111.133, 185.199.108.133, ...
Connecting to objects.githubusercontent.com (objects.githubusercontent.com)|185.199.110.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 8262584 (7.9M) [application/octet-stream]
Saving to: 'green_tripdata_2019-10.csv.gz'

     0K .......... .......... .......... .......... ..........  0%  228K 35s
    50K .......... .......... .......... .......... ..........  1%  358K 29s
   100K .......... .......... .......... .......... ..........  1%  760K 22s
   150K .......... .......... .......... .......... ..........  2%  210K 26s
   200K .......... .......... .......... .......... ..........  3%  396K 25s
   250K .......... .......... .......... .......... ..........  3%  220K 26s
   300K .......... .......... .......... .......... ..........  4%  478K 25s
   350K .......... .......... .......... .......... ..........  4%  232K 26s
   400K .......... .......... .......... .......... ..........  5%  220K 26s
   450K .......... .......... .......... .......... ..........  6%  292K 26s
   500K .......... .......... .......... .......... ..........  6%  244K 27s
   550K .......... .......... .......... .......... ..........  7%  278K 26s
   600K .......... .......... .......... .......... ..........  8%  268K 26s
   650K .......... .......... .......... .......... ..........  8%  191K 27s
   700K .......... .......... .......... .......... ..........  9%  239K 27s
   750K .......... .......... .......... .......... ..........  9%  452K 26s
   800K .......... .......... .......... .......... .......... 10%  167K 27s
   850K .......... .......... .......... .......... .......... 11%  283K 27s
   900K .......... .......... .......... .......... .......... 11%  156K 28s
   950K .......... .......... .......... .......... .......... 12%  362K 27s
  1000K .......... .......... .......... .......... .......... 13%  333K 27s
  1050K .......... .......... .......... .......... .......... 13%  112K 28s
  1100K .......... .......... .......... .......... .......... 14%  356K 27s
  1150K .......... .......... .......... .......... .......... 14%  205K 28s
  1200K .......... .......... .......... .......... .......... 15%  177K 28s
  1250K .......... .......... .......... .......... .......... 16%  253K 28s
  1300K .......... .......... .......... .......... .......... 16%  268K 27s
  1350K .......... .......... .......... .......... .......... 17%  206K 27s
  1400K .......... .......... .......... .......... .......... 17%  373K 27s
  1450K .......... .......... .......... .......... .......... 18%  172K 27s
  1500K .......... .......... .......... .......... .......... 19%  232K 27s
  1550K .......... .......... .......... .......... .......... 19%  237K 27s
  1600K .......... .......... .......... .......... .......... 20%  200K 27s
  1650K .......... .......... .......... .......... .......... 21%  164K 27s
  1700K .......... .......... .......... .......... .......... 21%  153K 27s
  1750K .......... .......... .......... .......... .......... 22%  119K 27s
  1800K .......... .......... .......... .......... .......... 22%  106K 28s
  1850K .......... .......... .......... .......... .......... 23% 65.5K 30s
  1900K .......... .......... .......... .......... .......... 24%  195K 29s
  1950K .......... .......... .......... .......... .......... 24%  150K 29s
  2000K .......... .......... .......... .......... .......... 25%  194K 29s
  2050K .......... .......... .......... .......... .......... 26%  208K 29s
  2100K .......... .......... .......... .......... .......... 26%  175K 29s
  2150K .......... .......... .......... .......... .......... 27%  108K 29s
  2200K .......... .......... .......... .......... .......... 27%  291K 29s
  2250K .......... .......... .......... .......... .......... 28%  138K 29s
  2300K .......... .......... .......... .......... .......... 29%  349K 28s
  2350K .......... .......... .......... .......... .......... 29%  195K 28s
  2400K .......... .......... .......... .......... .......... 30%  273K 28s
  2450K .......... .......... .......... .......... .......... 30%  206K 27s
  2500K .......... .......... .......... .......... .......... 31% 98.9K 28s
  2550K .......... .......... .......... .......... .......... 32%  263K 27s
  2600K .......... .......... .......... .......... .......... 32%  146K 27s
  2650K .......... .......... .......... .......... .......... 33%  196K 27s
  2700K .......... .......... .......... .......... .......... 34%  154K 27s
  2750K .......... .......... .......... .......... .......... 34%  142K 27s
  2800K .......... .......... .......... .......... .......... 35%  230K 27s
  2850K .......... .......... .......... .......... .......... 35%  174K 26s
  2900K .......... .......... .......... .......... .......... 36%  152K 26s
  2950K .......... .......... .......... .......... .......... 37%  159K 26s
  3000K .......... .......... .......... .......... .......... 37%  170K 26s
  3050K .......... .......... .......... .......... .......... 38%  262K 25s
  3100K .......... .......... .......... .......... .......... 39%  208K 25s
  3150K .......... .......... .......... .......... .......... 39%  249K 25s
  3200K .......... .......... .......... .......... .......... 40%  284K 24s
  3250K .......... .......... .......... .......... .......... 40%  373K 24s
  3300K .......... .......... .......... .......... .......... 41%  174K 24s
  3350K .......... .......... .......... .......... .......... 42%  300K 23s
  3400K .......... .......... .......... .......... .......... 42%  189K 23s
  3450K .......... .......... .......... .......... .......... 43%  185K 23s
  3500K .......... .......... .......... .......... .......... 43%  184K 23s
  3550K .......... .......... .......... .......... .......... 44%  188K 23s
  3600K .......... .......... .......... .......... .......... 45%  120K 23s
  3650K .......... .......... .......... .......... .......... 45%  236K 22s
  3700K .......... .......... .......... .......... .......... 46%  155K 22s
  3750K .......... .......... .......... .......... .......... 47%  239K 22s
  3800K .......... .......... .......... .......... .......... 47%  186K 21s
  3850K .......... .......... .......... .......... .......... 48%  110K 21s
  3900K .......... .......... .......... .......... .......... 48%  200K 21s
  3950K .......... .......... .......... .......... .......... 49%  370K 21s
  4000K .......... .......... .......... .......... .......... 50%  183K 21s
  4050K .......... .......... .......... .......... .......... 50%  275K 20s
  4100K .......... .......... .......... .......... .......... 51%  148K 20s
  4150K .......... .......... .......... .......... .......... 52%  248K 20s
  4200K .......... .......... .......... .......... .......... 52%  121K 20s
  4250K .......... .......... .......... .......... .......... 53%  335K 19s
  4300K .......... .......... .......... .......... .......... 53%  179K 19s
  4350K .......... .......... .......... .......... .......... 54%  102K 19s
  4400K .......... .......... .......... .......... .......... 55%  212K 19s
  4450K .......... .......... .......... .......... .......... 55%  102K 19s
  4500K .......... .......... .......... .......... .......... 56%  183K 18s
  4550K .......... .......... .......... .......... .......... 57%  123K 18s
  4600K .......... .......... .......... .......... .......... 57%  204K 18s
  4650K .......... .......... .......... .......... .......... 58%  131K 18s
  4700K .......... .......... .......... .......... .......... 58%  238K 17s
  4750K .......... .......... .......... .......... .......... 59%  146K 17s
  4800K .......... .......... .......... .......... .......... 60%  185K 17s
  4850K .......... .......... .......... .......... .......... 60%  158K 17s
  4900K .......... .......... .......... .......... .......... 61%  184K 17s
  4950K .......... .......... .......... .......... .......... 61%  194K 16s
  5000K .......... .......... .......... .......... .......... 62%  300K 16s
  5050K .......... .......... .......... .......... .......... 63%  174K 16s
  5100K .......... .......... .......... .......... .......... 63%  349K 15s
  5150K .......... .......... .......... .......... .......... 64% 85.4K 15s
  5200K .......... .......... .......... .......... .......... 65%  236K 15s
  5250K .......... .......... .......... .......... .......... 65%  147K 15s
  5300K .......... .......... .......... .......... .......... 66%  211K 14s
  5350K .......... .......... .......... .......... .......... 66%  143K 14s
  5400K .......... .......... .......... .......... .......... 67%  165K 14s
  5450K .......... .......... .......... .......... .......... 68%  167K 14s
  5500K .......... .......... .......... .......... .......... 68%  171K 13s
  5550K .......... .......... .......... .......... .......... 69%  252K 13s
  5600K .......... .......... .......... .......... .......... 70%  157K 13s
  5650K .......... .......... .......... .......... .......... 70%  291K 13s
  5700K .......... .......... .......... .......... .......... 71%  374K 12s
  5750K .......... .......... .......... .......... .......... 71%  266K 12s
  5800K .......... .......... .......... .......... .......... 72%  244K 12s
  5850K .......... .......... .......... .......... .......... 73%  271K 11s
  5900K .......... .......... .......... .......... .......... 73%  257K 11s
  5950K .......... .......... .......... .......... .......... 74%  228K 11s
  6000K .......... .......... .......... .......... .......... 74%  296K 11s
  6050K .......... .......... .......... .......... .......... 75%  264K 10s
  6100K .......... .......... .......... .......... .......... 76%  247K 10s
  6150K .......... .......... .......... .......... .......... 76%  213K 10s
  6200K .......... .......... .......... .......... .......... 77%  117K 10s
  6250K .......... .......... .......... .......... .......... 78%  300K 9s
  6300K .......... .......... .......... .......... .......... 78%  178K 9s
  6350K .......... .......... .......... .......... .......... 79%  252K 9s
  6400K .......... .......... .......... .......... .......... 79%  265K 8s
  6450K .......... .......... .......... .......... .......... 80%  265K 8s
  6500K .......... .......... .......... .......... .......... 81%  177K 8s
  6550K .......... .......... .......... .......... .......... 81%  186K 8s
  6600K .......... .......... .......... .......... .......... 82%  205K 7s
  6650K .......... .......... .......... .......... .......... 83%  200K 7s
  6700K .......... .......... .......... .......... .......... 83%  319K 7s
  6750K .......... .......... .......... .......... .......... 84%  182K 7s
  6800K .......... .......... .......... .......... .......... 84%  207K 6s
  6850K .......... .......... .......... .......... .......... 85%  455K 6s
  6900K .......... .......... .......... .......... .......... 86%  193K 6s
  6950K .......... .......... .......... .......... .......... 86%  350K 5s
  7000K .......... .......... .......... .......... .......... 87%  376K 5s
  7050K .......... .......... .......... .......... .......... 87%  214K 5s
  7100K .......... .......... .......... .......... .......... 88%  466K 5s
  7150K .......... .......... .......... .......... .......... 89%  208K 4s
  7200K .......... .......... .......... .......... .......... 89%  201K 4s
  7250K .......... .......... .......... .......... .......... 90%  289K 4s
  7300K .......... .......... .......... .......... .......... 91%  204K 4s
  7350K .......... .......... .......... .......... .......... 91%  160K 3s
  7400K .......... .......... .......... .......... .......... 92%  233K 3s
  7450K .......... .......... .......... .......... .......... 92%  280K 3s
  7500K .......... .......... .......... .......... .......... 93%  186K 3s
  7550K .......... .......... .......... .......... .......... 94%  371K 2s
  7600K .......... .......... .......... .......... .......... 94%  167K 2s
  7650K .......... .......... .......... .......... .......... 95%  281K 2s
  7700K .......... .......... .......... .......... .......... 96%  159K 2s
  7750K .......... .......... .......... .......... .......... 96%  358K 1s
  7800K .......... .......... .......... .......... .......... 97%  196K 1s
  7850K .......... .......... .......... .......... .......... 97%  163K 1s
  7900K .......... .......... .......... .......... .......... 98%  281K 1s
  7950K .......... .......... .......... .......... .......... 99%  108K 0s
  8000K .......... .......... .......... .......... .......... 99%  168K 0s
  8050K .......... ........                                   100%  539K=41s

2025-01-25 15:18:32 (197 KB/s) - 'green_tripdata_2019-10.csv.gz' saved [8262584/8262584]

In [3]:
!wget https://github.com/DataTalksClub/nyc-tlc-data/releases/download/misc/taxi_zone_lookup.csv

--2025-01-25 15:18:32--  https://github.com/DataTalksClub/nyc-tlc-data/releases/download/misc/taxi_zone_lookup.csv
Resolving github.com (github.com)... 140.82.121.4
Connecting to github.com (github.com)|140.82.121.4|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://objects.githubusercontent.com/github-production-release-asset-2e65be/513814948/5a2cc2f5-b4cd-4584-9c62-a6ea97ed0e6a?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=releaseassetproduction%2F20250125%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20250125T121833Z&X-Amz-Expires=300&X-Amz-Signature=60ac4ff4e476f821d6532dcf83299ab77b22352217fab70c4528986ca7c1b3ef&X-Amz-SignedHeaders=host&response-content-disposition=attachment%3B%20filename%3Dtaxi_zone_lookup.csv&response-content-type=application%2Foctet-stream [following]
--2025-01-25 15:18:34--  https://objects.githubusercontent.com/github-production-release-asset-2e65be/513814948/5a2cc2f5-b4cd-4584-9c62-a6ea97ed0e6a?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=releaseassetproduction%2F20250125%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20250125T121833Z&X-Amz-Expires=300&X-Amz-Signature=60ac4ff4e476f821d6532dcf83299ab77b22352217fab70c4528986ca7c1b3ef&X-Amz-SignedHeaders=host&response-content-disposition=attachment%3B%20filename%3Dtaxi_zone_lookup.csv&response-content-type=application%2Foctet-stream
Resolving objects.githubusercontent.com (objects.githubusercontent.com)... 185.199.110.133, 185.199.111.133, 185.199.108.133, ...
Connecting to objects.githubusercontent.com (objects.githubusercontent.com)|185.199.110.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 12322 (12K) [application/octet-stream]
Saving to: 'taxi_zone_lookup.csv.1'

     0K .......... ..                                         100%  126K=0.1s

2025-01-25 15:18:35 (126 KB/s) - 'taxi_zone_lookup.csv.1' saved [12322/12322]

In [5]:
import pandas as pd
from sqlalchemy import create_engine

In [7]:
df = pd.read_csv('green_tripdata_2019-10.csv', nrows=100)

In [8]:
df

,VendorID,lpep_pickup_datetime,lpep_dropoff_datetime,store_and_fwd_flag,RatecodeID,PULocationID,DOLocationID,passenger_count,trip_distance,fare_amount,extra,mta_tax,tip_amount,tolls_amount,ehail_fee,improvement_surcharge,total_amount,payment_type,trip_type,congestion_surcharge
0,2,2019-10-01 00:26:02,2019-10-01 00:39:58,N,1,112,196,1,5.88,18.0,0.50,0.5,0.00,0.0,NaN,0.3,19.30,2,1,0.0
1,1,2019-10-01 00:18:11,2019-10-01 00:22:38,N,1,43,263,1,0.80,5.0,3.25,0.5,0.00,0.0,NaN,0.3,9.05,2,1,0.0
2,1,2019-10-01 00:09:31,2019-10-01 00:24:47,N,1,255,228,2,7.50,21.5,0.50,0.5,0.00,0.0,NaN,0.3,22.80,2,1,0.0
3,1,2019-10-01 00:37:40,2019-10-01 00:41:49,N,1,181,181,1,0.90,5.5,0.50,0.5,0.00,0.0,NaN,0.3,6.80,2,1,0.0
4,2,2019-10-01 00:08:13,2019-10-01 00:17:56,N,1,97,188,1,2.52,10.0,0.50,0.5,2.26,0.0,NaN,0.3,13.56,1,1,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,2,2019-10-01 00:02:53,2019-10-01 00:14:32,N,1,126,74,1,3.10,12.0,0.50,0.5,0.00,0.0,NaN,0.3,13.30,1,1,0.0
96,2,2019-10-01 00:18:45,2019-10-01 00:29:23,N,1,42,74,1,1.64,9.5,0.50,0.5,0.00,0.0,NaN,0.3,10.80,2,1,0.0
97,2,2019-10-01 00:41:32,2019-10-01 00:52:51,N,1,75,42,1,3.17,11.5,0.50,0.5,1.50,0.0,NaN,0.3,14.30,1,1,0.0
98,2,2019-10-01 00:36:54,2019-10-01 00:54:20,N,1,92,179,1,5.48,19.5,0.50,0.5,0.00,0.0,NaN,0.3,20.80,2,1,0.0
99,2,2019-10-01 00:21:27,2019-10-01 00:26:59,N,1,129,129,1,1.02,6.0,0.50,0.5,0.00,0.0,NaN,0.3,7.30,2,1,0.0

In [10]:
df.lpep_pickup_datetime = pd.to_datetime(df.lpep_pickup_datetime)
df.lpep_dropoff_datetime = pd.to_datetime(df.lpep_dropoff_datetime)

In [11]:
engine = create_engine('postgresql://root:root@localhost:5432/ny_taxi')

In [12]:
print(pd.io.sql.get_schema(df, name='green_taxi_data', con=engine))

CREATE TABLE green_taxi_data (
	"VendorID" BIGINT,
	lpep_pickup_datetime TIMESTAMP WITHOUT TIME ZONE,
	lpep_dropoff_datetime TIMESTAMP WITHOUT TIME ZONE,
	store_and_fwd_flag TEXT,
	"RatecodeID" BIGINT,
	"PULocationID" BIGINT,
	"DOLocationID" BIGINT,
	passenger_count BIGINT,
	trip_distance FLOAT(53),
	fare_amount FLOAT(53),
	extra FLOAT(53),
	mta_tax FLOAT(53),
	tip_amount FLOAT(53),
	tolls_amount FLOAT(53),
	ehail_fee FLOAT(53),
	improvement_surcharge FLOAT(53),
	total_amount FLOAT(53),
	payment_type BIGINT,
	trip_type BIGINT,
	congestion_surcharge FLOAT(53)
)

In [13]:
df_iter = pd.read_csv('green_tripdata_2019-10.csv', iterator=True, chunksize=100000)

In [14]:
from time import time
while True: 
    t_start = time()

    df = next(df_iter)

    df.lpep_pickup_datetime = pd.to_datetime(df.lpep_pickup_datetime)
    df.lpep_dropoff_datetime = pd.to_datetime(df.lpep_dropoff_datetime)
    
    df.to_sql(name='green_taxi_data', con=engine, if_exists='append')

    t_end = time()

    print('inserted another chunk, took %.3f second' % (t_end - t_start))

inserted another chunk, took 30.805 second
inserted another chunk, took 31.852 second
inserted another chunk, took 22.591 second

C:\Users\User\AppData\Local\Temp\ipykernel_10124\971209448.py:5: DtypeWarning: Columns (3) have mixed types. Specify dtype option on import or set low_memory=False.
  df = next(df_iter)

inserted another chunk, took 23.082 second
inserted another chunk, took 17.580 second

StopIteration:

In [ ]:
df_zones = pd.read_csv("taxi_zone_lookup.csv")
df_zones.to_sql(name='zones', con=engine, if_exists='replace')

In [15]:
print(pd.io.sql.get_schema(df, name='zones', con=engine))

CREATE TABLE zones (
	"VendorID" FLOAT(53),
	lpep_pickup_datetime TIMESTAMP WITHOUT TIME ZONE,
	lpep_dropoff_datetime TIMESTAMP WITHOUT TIME ZONE,
	store_and_fwd_flag FLOAT(53),
	"RatecodeID" FLOAT(53),
	"PULocationID" BIGINT,
	"DOLocationID" BIGINT,
	passenger_count FLOAT(53),
	trip_distance FLOAT(53),
	fare_amount FLOAT(53),
	extra FLOAT(53),
	mta_tax FLOAT(53),
	tip_amount FLOAT(53),
	tolls_amount FLOAT(53),
	ehail_fee FLOAT(53),
	improvement_surcharge FLOAT(53),
	total_amount FLOAT(53),
	payment_type FLOAT(53),
	trip_type FLOAT(53),
	congestion_surcharge FLOAT(53)
)

In [ ]:
SELECT
    COUNT(*) FILTER (WHERE trip_distance <= 1) AS trips_up_to_1_mile,
    COUNT(*) FILTER (WHERE trip_distance > 1 AND trip_distance <= 3) AS trips_1_to_3_miles,
    COUNT(*) FILTER (WHERE trip_distance > 3 AND trip_distance <= 7) AS trips_3_to_7_miles,
    COUNT(*) FILTER (WHERE trip_distance > 7 AND trip_distance <= 10) AS trips_7_to_10_miles,
    COUNT(*) FILTER (WHERE trip_distance > 10) AS trips_over_10_miles
FROM green_taxi_data
WHERE lpep_pickup_datetime >= '2019-10-01' 
  AND lpep_pickup_datetime < '2019-11-01';

In [ ]:
WITH longest_trip_per_day AS (
    SELECT
        DATE(lpep_pickup_datetime) AS pickup_day,
        MAX(trip_distance) AS longest_distance
    FROM green_taxi_data
    GROUP BY DATE(lpep_pickup_datetime)
)
SELECT
    pickup_day,
    longest_distance
FROM longest_trip_per_day
ORDER BY longest_distance DESC
LIMIT 1;

In [ ]:
SELECT
    "PULocationID" AS pickup_location,
    SUM(total_amount) AS total_amount
FROM green_taxi_data
WHERE DATE(lpep_pickup_datetime) = '2019-10-18'
GROUP BY "PULocationID"
HAVING SUM(total_amount) > 13000
ORDER BY total_amount DESC;

In [ ]:
WITH top_pickup_locations AS (
    SELECT
        "PULocationID" AS pickup_location,
        SUM(total_amount) AS total_amount
    FROM green_taxi_data
    WHERE DATE(lpep_pickup_datetime) = '2019-10-18'
    GROUP BY "PULocationID"
    HAVING SUM(total_amount) > 13000
)
SELECT
    z."Zone" AS pickup_zone_name,
    tpl.total_amount
FROM top_pickup_locations tpl
JOIN zones z ON tpl.pickup_location = z."LocationID"
ORDER BY tpl.total_amount DESC;

In [ ]:
WITH east_harlem_pickups AS (
    SELECT
        g."DOLocationID",
        g.trip_distance
    FROM green_taxi_data g
    JOIN zones z ON g."PULocationID" = z."LocationID"
    WHERE z."Zone" = 'East Harlem North'
      AND DATE_TRUNC('month', g.lpep_pickup_datetime) = '2019-10-01'
)
SELECT
    z."Zone" AS dropoff_zone_name,
    MAX(ehp.trip_distance) AS largest_trip_distance
FROM east_harlem_pickups ehp
JOIN zones z ON ehp."DOLocationID" = z."LocationID"
GROUP BY z."Zone"
ORDER BY largest_trip_distance DESC
LIMIT 1;